import { Alert, HelmetDevice, DetectionEvent, SystemMetrics, ApiEndpoint } from '../types';

export const mockAlerts: Alert[] = [
  {
    id: 'ALT-001',
    type: 'drowsiness',
    severity: 'critical',
    message: 'High drowsiness detected — Eye closure duration exceeded 3 seconds',
    timestamp: new Date(Date.now() - 1000 * 60 * 2),
    location: 'NH-48, Bangalore',
    helmetId: 'HLM-003',
    acknowledged: false,
    smsSent: true,
    firebaseLogged: true,
  },
  {
    id: 'ALT-002',
    type: 'accident',
    severity: 'critical',
    message: 'Sudden impact detected — Accelerometer spike > 4G on all axes',
    timestamp: new Date(Date.now() - 1000 * 60 * 8),
    location: 'Ring Road, Hyderabad',
    helmetId: 'HLM-001',
    acknowledged: true,
    smsSent: true,
    firebaseLogged: true,
  },
  {
    id: 'ALT-003',
    type: 'alcohol',
    severity: 'warning',
    message: 'Alcohol detected — BAC level 0.06% above safe threshold',
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
    location: 'MG Road, Pune',
    helmetId: 'HLM-002',
    acknowledged: false,
    smsSent: true,
    firebaseLogged: true,
  },
  {
    id: 'ALT-004',
    type: 'drowsiness',
    severity: 'warning',
    message: 'Moderate drowsiness — Yawning frequency increased, eye aspect ratio dropping',
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
    location: 'NICE Road, Bangalore',
    helmetId: 'HLM-005',
    acknowledged: true,
    smsSent: false,
    firebaseLogged: true,
  },
  {
    id: 'ALT-005',
    type: 'system',
    severity: 'info',
    message: 'Firebase connection established — Real-time sync active',
    timestamp: new Date(Date.now() - 1000 * 60 * 45),
    helmetId: 'SYSTEM',
    acknowledged: true,
    smsSent: false,
    firebaseLogged: false,
  },
  {
    id: 'ALT-006',
    type: 'alcohol',
    severity: 'critical',
    message: 'High BAC detected — 0.12% — Engine lock triggered',
    timestamp: new Date(Date.now() - 1000 * 60 * 60),
    location: 'Outer Ring Road, Delhi',
    helmetId: 'HLM-004',
    acknowledged: true,
    smsSent: true,
    firebaseLogged: true,
  },
  {
    id: 'ALT-007',
    type: 'drowsiness',
    severity: 'info',
    message: 'Drowsiness early warning — Recommended rest break in 10 minutes',
    timestamp: new Date(Date.now() - 1000 * 60 * 90),
    location: 'Mumbai-Pune Expressway',
    helmetId: 'HLM-006',
    acknowledged: true,
    smsSent: false,
    firebaseLogged: true,
  },
];

export const mockHelmets: HelmetDevice[] = [
  {
    id: 'HLM-001',
    name: 'SmartHelmet Alpha',
    rider: 'Arjun Sharma',
    status: 'online',
    battery: 87,
    location: 'Ring Road, Hyderabad',
    lastSeen: new Date(Date.now() - 1000 * 30),
    drowsinessScore: 12,
    alcoholLevel: 0.0,
    accelerometerData: { x: 0.1, y: 0.2, z: 9.8 },
    isActive: true,
  },
  {
    id: 'HLM-002',
    name: 'SmartHelmet Beta',
    rider: 'Priya Nair',
    status: 'online',
    battery: 63,
    location: 'MG Road, Pune',
    lastSeen: new Date(Date.now() - 1000 * 45),
    drowsinessScore: 34,
    alcoholLevel: 0.06,
    accelerometerData: { x: 0.3, y: -0.1, z: 9.7 },
    isActive: true,
  },
  {
    id: 'HLM-003',
    name: 'SmartHelmet Gamma',
    rider: 'Ravi Kumar',
    status: 'online',
    battery: 42,
    location: 'NH-48, Bangalore',
    lastSeen: new Date(Date.now() - 1000 * 10),
    drowsinessScore: 78,
    alcoholLevel: 0.01,
    accelerometerData: { x: 0.5, y: 0.4, z: 9.6 },
    isActive: true,
  },
  {
    id: 'HLM-004',
    name: 'SmartHelmet Delta',
    rider: 'Meena Patel',
    status: 'offline',
    battery: 15,
    location: 'Outer Ring Road, Delhi',
    lastSeen: new Date(Date.now() - 1000 * 60 * 62),
    drowsinessScore: 0,
    alcoholLevel: 0.12,
    accelerometerData: { x: 0, y: 0, z: 0 },
    isActive: false,
  },
  {
    id: 'HLM-005',
    name: 'SmartHelmet Epsilon',
    rider: 'Vikram Singh',
    status: 'online',
    battery: 95,
    location: 'NICE Road, Bangalore',
    lastSeen: new Date(Date.now() - 1000 * 20),
    drowsinessScore: 45,
    alcoholLevel: 0.0,
    accelerometerData: { x: 0.2, y: 0.1, z: 9.8 },
    isActive: true,
  },
  {
    id: 'HLM-006',
    name: 'SmartHelmet Zeta',
    rider: 'Sunita Reddy',
    status: 'connecting',
    battery: 71,
    location: 'Mumbai-Pune Expressway',
    lastSeen: new Date(Date.now() - 1000 * 120),
    drowsinessScore: 22,
    alcoholLevel: 0.0,
    accelerometerData: { x: 0.1, y: 0.0, z: 9.9 },
    isActive: false,
  },
];

export const generateDetectionHistory = (): DetectionEvent[] => {
  const now = Date.now();
  return Array.from({ length: 24 }, (_, i) => ({
    timestamp: new Date(now - (23 - i) * 1000 * 60 * 30),
    drowsinessLevel: Math.floor(Math.random() * 80) + 5,
    alcoholLevel: Math.random() * 0.08,
    accidentRisk: Math.floor(Math.random() * 60) + 5,
  }));
};

export const mockSystemMetrics: SystemMetrics = {
  totalAlerts: 142,
  smsSent: 87,
  firebaseEvents: 1248,
  activeHelmets: 4,
  uptime: '99.8%',
  apiStatus: {
    flask: 'online',
    firebase: 'online',
    twilio: 'online',
    ai: 'online',
  },
};

export const mockApiEndpoints: ApiEndpoint[] = [
  {
    method: 'GET',
    path: '/health',
    description: 'Backend health check & service status',
    status: 'active',
    lastCalled: new Date(Date.now() - 1000 * 30),
    responseTime: 12,
  },
  {
    method: 'POST',
    path: '/api/alerts/sms',
    description: 'Send SMS alert via Twilio',
    status: 'active',
    lastCalled: new Date(Date.now() - 1000 * 60 * 2),
    responseTime: 340,
  },
  {
    method: 'POST',
    path: '/api/ai/drowsiness',
    description: 'Drowsiness detection trigger',
    status: 'active',
    lastCalled: new Date(Date.now() - 1000 * 60 * 5),
    responseTime: 89,
  },
  {
    method: 'POST',
    path: '/api/ai/accident',
    description: 'Accident classification endpoint',
    status: 'active',
    lastCalled: new Date(Date.now() - 1000 * 60 * 8),
    responseTime: 124,
  },
  {
    method: 'POST',
    path: '/api/ai/alcohol',
    description: 'Alcohol detection endpoint',
    status: 'active',
    lastCalled: new Date(Date.now() - 1000 * 60 * 15),
    responseTime: 67,
  },
  {
    method: 'POST',
    path: '/api/firebase/log',
    description: 'Log event to Firebase database',
    status: 'active',
    lastCalled: new Date(Date.now() - 1000 * 45),
    responseTime: 210,
  },
  {
    method: 'GET',
    path: '/api/helmets',
    description: 'Get all connected helmet devices',
    status: 'pending',
    responseTime: undefined,
  },
  {
    method: 'GET',
    path: '/api/alerts/history',
    description: 'Fetch alert history from Firebase',
    status: 'pending',
    responseTime: undefined,
  },
];

export const weeklyAlertData = [
  { day: 'Mon', drowsiness: 8, accident: 2, alcohol: 3 },
  { day: 'Tue', drowsiness: 12, accident: 1, alcohol: 5 },
  { day: 'Wed', drowsiness: 6, accident: 3, alcohol: 2 },
  { day: 'Thu', drowsiness: 15, accident: 0, alcohol: 7 },
  { day: 'Fri', drowsiness: 10, accident: 4, alcohol: 9 },
  { day: 'Sat', drowsiness: 18, accident: 2, alcohol: 12 },
  { day: 'Sun', drowsiness: 7, accident: 1, alcohol: 4 },
];

export const hourlyRiskData = Array.from({ length: 24 }, (_, i) => ({
  hour: `${i.toString().padStart(2, '0')}:00`,
  risk: i >= 0 && i <= 5 ? Math.floor(Math.random() * 60) + 40
       : i >= 22 ? Math.floor(Math.random() * 50) + 35
       : Math.floor(Math.random() * 30) + 10,
}));
